version: '3.9'

services:

  frontend_web:
    container_name: youtube-clone-frontend-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
    - .:/app
    - '/app/node_modules'
    ports:
      - '3002:3000'

