version: '3.9'

services:

  frontend_web:
    container_name: youtube-clone-frontend_web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
      - '/app/node_modules'
      - .:/app