version: '3.9'

services:

  frontend_web:
    container_name: youtube-clone-frontend-dev
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    volumes:
    - .:/app
    - '/app/node_modules'
    ports:
      - '3002:3000'

  frontend_test:
    container_name: youtube-clone-frontend_web
    depends_on:
      - "frontend_web"
    image: youtube-clone-frontend_frontend_web
    volumes:
     - .:/app
     - '/app/node_modules'
    command: ["npm", "run", "test"]