name: Docker Dev Image CI

on:
  pull_request:
    branches: [main]
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run docker compose on dev files
      run: docker-compose -f "docker-compose-dev.yml" up -d --build

    - name: Auto-Merge Pull Request
      uses: reitermarkus/automerge@v1.5.2

    - name: Bump version number
      run: npm version patch
      with:
        git config --global user.email "brennanknopf@gmail.com"
        git config --global user.name "brennanknopf"

    


   
    





     
