name: Docker Dev Image CI

env:
  DATE_STAMP: $(date +%s)

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2

     - name: Build the Docker image
       run: docker-compose -f "docker-compose-dev.yml"  -t "brennanknopf/ytc-frontend:latest"

    #  - name: Run Docker compose on Dev files
    #    run: docker-compose -f "docker-compose-dev.yml" up -d --build "my-awesome-app-bwk"
     
     - name: Env variables
       run: echo "date-stamp=${{env.DATE_STAMP}}" >> $GITHUB_ENV
       
     - name: Add "date-stamp" tag to the image
       run: docker image tag brennanknopf/my-awesome-app-bwk:latest brennanknopf/my-awesome-app-bwk:${{env.date-stamp}}
       
     - name: login to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
    
     - name: Push the Docker image to Docker Hub
       run: docker push --all-tags brennanknopf/my-awesome-app-bwk
